# Generated by Django 5.1.4 on 2024-12-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anomaly',
            table='Anomaly',
        ),
        migrations.AlterModelTable(
            name='modeltraining',
            table='ModelTraining',
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='Sensor',
        ),
        migrations.AlterModelTable(
            name='sensordata',
            table='SensorData',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
